## Convolution

In [1]:
import torch
import torch.nn as nn

# Create input tensor
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
print("Input:")
print(input)

# Define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,  # Create a kernel of size 3x3
    bias=False
)

# Random initialization of kernel weights
init_kernel_weight = torch.randint(
    high=2,
    size=(conv_layer.weight.data.shape),
    dtype=torch.float32
)
print("Initial Kernel Weight:")
print(init_kernel_weight)

# Initialize the convolutional layer weights
conv_layer.weight.data = init_kernel_weight
print("Convolutional Layer Weights:")
print(conv_layer.weight)

# Apply convolution
output = conv_layer(input)
print("Output:")
print(output)

Input:
tensor([[[4., 2., 3., 1., 1., 2.],
         [1., 0., 2., 2., 3., 1.],
         [4., 3., 0., 1., 3., 0.],
         [0., 2., 2., 3., 1., 4.],
         [0., 2., 3., 0., 4., 4.],
         [4., 1., 2., 2., 3., 2.]]])
Initial Kernel Weight:
tensor([[[[1., 0., 0.],
          [1., 0., 0.],
          [0., 0., 1.]]]])
Convolutional Layer Weights:
Parameter containing:
tensor([[[[1., 0., 0.],
          [1., 0., 0.],
          [0., 0., 1.]]]], requires_grad=True)
Output:
tensor([[[5., 3., 8., 3.],
         [7., 6., 3., 7.],
         [7., 5., 6., 8.],
         [2., 6., 8., 5.]]], grad_fn=<SqueezeBackward1>)


## Padding

In [2]:
import torch
import torch.nn as nn

# Tạo tensor đầu vào ngẫu nhiên
input = torch.randint(5, (1, 1, 4, 4), dtype=torch.float32)
print("Input:")
print(input)

# Khởi tạo trọng số kernel ngẫu nhiên
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    padding='same'  # Sử dụng padding "same"
)

# Khởi tạo giá trị trọng số của kernel
init_kernel_weight = torch.randint(
    high=2,
    size=conv_layer.weight.data.shape,
    dtype=torch.float32
)
conv_layer.weight.data = init_kernel_weight
print("\nInitialized Kernel Weight:")
print(conv_layer.weight)

# Khởi tạo giá trị bias
conv_layer.bias = nn.Parameter(torch.tensor([1.], dtype=torch.float32))
print("\nInitialized Bias:")
print(conv_layer.bias)

# Thực hiện tích chập
output = conv_layer(input)
print("\nOutput:")
print(output)

Input:
tensor([[[[4., 3., 0., 1.],
          [3., 4., 4., 0.],
          [4., 2., 1., 1.],
          [2., 2., 1., 3.]]]])

Initialized Kernel Weight:
Parameter containing:
tensor([[[[0., 0., 1.],
          [0., 0., 1.],
          [1., 0., 0.]]]], requires_grad=True)

Initialized Bias:
Parameter containing:
tensor([1.], requires_grad=True)

Output:
tensor([[[[4., 4., 6., 5.],
          [8., 9., 4., 2.],
          [7., 8., 4., 2.],
          [5., 3., 5., 1.]]]], grad_fn=<ConvolutionBackward0>)


## Strike

In [3]:
import torch
import torch.nn as nn

# Tạo tensor đầu vào ngẫu nhiên với kích thước (1, 1, 6, 6)
input = torch.randint(5, (1, 1, 6, 6), dtype=torch.float32)
print("Input:")
print(input)

# Định nghĩa lớp convolutional layer với stride=2
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,  # Tạo kernel 3x3
    stride=2  # Sử dụng stride=2
)

# Khởi tạo trọng số kernel
init_kernel_weight = torch.tensor([[[[1., 1., 1.],
                                     [1., 1., 1.],
                                     [0., 1., 0.]]]], dtype=torch.float32)
conv_layer.weight.data = init_kernel_weight
print("\nInitialized Kernel Weight:")
print(conv_layer.weight)

# Khởi tạo bias
conv_layer.bias = nn.Parameter(torch.tensor([1.], dtype=torch.float32))
print("\nInitialized Bias:")
print(conv_layer.bias)

# Thực hiện tích chập
output = conv_layer(input)
print("\nOutput:")
print(output)

Input:
tensor([[[[1., 3., 3., 4., 4., 1.],
          [0., 1., 0., 4., 3., 1.],
          [1., 3., 2., 2., 2., 4.],
          [2., 2., 0., 4., 2., 0.],
          [0., 0., 3., 0., 1., 1.],
          [3., 2., 1., 2., 2., 1.]]]])

Initialized Kernel Weight:
Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [0., 1., 0.]]]], requires_grad=True)

Initialized Bias:
Parameter containing:
tensor([1.], requires_grad=True)

Output:
tensor([[[[12., 21.],
          [11., 13.]]]], grad_fn=<ConvolutionBackward0>)


## Polling

In [4]:
import torch
import torch.nn as nn

# Tạo tensor đầu vào
input = torch.tensor([[[3., 2., 1., 0., 0., 3.],
                       [0., 3., 3., 1., 1., 0.],
                       [3., 1., 4., 1., 1., 0.],
                       [2., 4., 1., 1., 0., 4.],
                       [1., 0., 3., 0., 3., 0.],
                       [3., 4., 4., 3., 3., 4.]]])

print("Input:")
print(input)

# Khởi tạo lớp Average Pooling với kernel size 3 và stride 3
avg_pool_layer = nn.AvgPool1d(
    kernel_size=3,
    stride=3
)

# Áp dụng Average Pooling lên đầu vào
output = avg_pool_layer(input)
print("\nOutput:")
print(output)

Input:
tensor([[[3., 2., 1., 0., 0., 3.],
         [0., 3., 3., 1., 1., 0.],
         [3., 1., 4., 1., 1., 0.],
         [2., 4., 1., 1., 0., 4.],
         [1., 0., 3., 0., 3., 0.],
         [3., 4., 4., 3., 3., 4.]]])

Output:
tensor([[[2.0000, 1.0000],
         [2.0000, 0.6667],
         [2.6667, 0.6667],
         [2.3333, 1.6667],
         [1.3333, 1.0000],
         [3.6667, 3.3333]]])


## Flatten


In [5]:
import torch
import torch.nn as nn

# Tạo tensor đầu vào
input = torch.randint(5, (1, 3, 2), dtype=torch.float32)
print("Input:")
print(input)

# Khởi tạo lớp Flatten
flatten_layer = nn.Flatten()

# Làm phẳng tensor đầu vào
output = flatten_layer(input)
print("\nOutput:")
print(output)

Input:
tensor([[[0., 0.],
         [4., 3.],
         [1., 0.]]])

Output:
tensor([[0., 0., 4., 3., 1., 0.]])
